### PR TITLE
Adds pass phrase support for `pass` file

### PR DESCRIPTION
**Pull request by OliverLetterer**

### CODE REVIEW

**Comment by danmilon** [comment]
I've got the password removed from my key, so I didn't think about this, but nice addition nonetheless!
Just some styling issues, left comments.
Fix, squash and should be good to merge!

**Comment by danmilon** [comment]
I'd prefer `password` instead of `passPhrase`, if you're ok with that.

**Comment by OliverLetterer** [comment]
I was using passPhrase because of [openssl terminology](http://www.openssl.org/docs/apps/smime.html), but i would be fine with password.

**Comment by danmilon** [comment]
Both are mentioned in the openssl docs, so I guess its a matter of preference. Lets go with `password`.

**Comment by OliverLetterer** [comment]
sure.

**Comment by OliverLetterer** [comment]
Any chance in seeing this merged or are there still any issues left?

**Comment by danmilon** [comment]
Ah, sorry. Didn't get an email about the new commits.
Yes, please squash all 6 of them into one commit, and write a comment when done.
Thanks!

**Pull request closed without merging**
